### ISSUE TITLE
App.config

### ISSUE THREAD

**Issue by pischky** [roydukkey/NHibernate-X-Factories#6]
Hi, 
would like to use this from App.config (....exe.config) for a Windows Service Application. Have tried but do not get it working. I followed your wiki article "Configuration from Web.Config" with using App.config instead of Web.config. But it does not compile because NHibernate.Cfg.Configuration.Configure does not have a version with two String parameters. I'm using NHibernate 3.4.0.0.
Thank you very much for any help, Martin

**Comment by roydukkey** [comment]
I'm just curious, but have you added the `ConfigurationExtensions.cs` into your project. There is a [extension method](https://github.com/roydukkey/NHibernate-X-Factories/blob/b22c073136799a7471e87f47d3811021e128ee54/ConfigurationExtensions.cs#L20-L34) that takes two string parameters.
