### ISSUE TITLE
Failed to connect to SQL2000

### ISSUE THREAD

**Issue by joseph60** [roydukkey/NHibernate-X-Factories#8]
I need to access 2 sql dbs, one is MS SQL 2014,I named it ACDS and the 2nd is an old ms sql2000,i named it EF.
I put everything into ,the nhibernate.cfg.xml, run from my own pc,it works.
Then i publish the service code to an winserver 2008,it failed to access the EF db,the error message looks like:
An exception of type 'System.Data.SqlClient.SqlException' occurred in NHibernate.dll but was not handled in user code.
it says failed to locate the db server(provider: SQL Network Interfaces, error: 26).

But the ACDS db works fine at the same time.
Then i move back to my PC,and change the configuration as the [Configuration from Web.Config] told,this time it failed with same error (provider: SQL Network Interfaces, error: 26).

If i move the config data back to the nhibernate.cfg.xml file from the web.config,every thing works fine in my pc.

**Comment by roydukkey** [comment]
Can you please leave your config file and code. Thanks.

**Comment by joseph60** [comment]
Thanks.
My nhibernate.cfg.xml:

<hibernate-configuration-x-factories xmlns="urn:nhibernate-configuration-2.2-x-factories">
  <session-factory name="ads">
    <property name="connection.provider">NHibernate.Connection.DriverConnectionProvider</property>
    <property name="dialect">NHibernate.Dialect.MsSql2012Dialect</property>
    <property name="connection.driver_class">NHibernate.Driver.SqlClientDriver</property>
    <property name="connection.connection_string">server=ads;database=vs2015;uid=sa;pwd=saads;</property>
    <property name="show_sql">true</property>
  </session-factory>
  <session-factory name="EF2K">
    <property name="connection.provider">NHibernate.Connection.DriverConnectionProvider</property>
    <property name="dialect">NHibernate.Dialect.MsSql2000Dialect</property>
    <property name="connection.driver_class">NHibernate.Driver.SqlClientDriver</property>
    <property name="connection.connection_string">server=db110\\dbsql2k;database=PCAR;uid=sa;pwd=sa2000;</property>
    <property name="show_sql">true</property>
  </session-factory>
  </hibernate-configuration-x-factories>


my NHibernateHelper Class:

private static ISessionFactory SessionFactories
        {
            get
            {
                if (_sessionFactories.Count == 0 || !_sessionFactories.ContainsKey(catagory))
                {
                    NHibernate.Cfg.Configuration configuration = new NHibernate.Cfg.Configuration();
                    configuration.Configure(HostingEnvironment.MapPath("~/nhibernate.cfg.xml"), catagory);

                    configuration.AddAssembly(typeof(OrderInfo).Assembly);
                    _sessionFactory = configuration.BuildSessionFactory();  /*******/
                    _sessionFactories.Add(catagory, _sessionFactory);
                }
                return _sessionFactories[catagory];
            }
        }



This works with my win7+visual studio 2015,but fails with my windows server 2008(no Visual Studio installed)

**Comment by joseph60** [comment]
if i move the to web.config ,it will not work in my win7 system.

web.config:

<configuration>
  <configSections>
    <section name="hibernate-configuration-x-factories" type="NHibernate.Cfg.ConfigurationSectionHandler, NHibernate" />
  </configSections>
  <hibernate-configuration-x-factories xmlns="urn:nhibernate-configuration-2.2-x-factories">
     <session-factory name="ads">
    <property name="connection.provider">NHibernate.Connection.DriverConnectionProvider</property>
    <property name="dialect">NHibernate.Dialect.MsSql2012Dialect</property>
    <property name="connection.driver_class">NHibernate.Driver.SqlClientDriver</property>
    <property name="connection.connection_string">server=ads;database=vs2015;uid=sa;pwd=saads;</property>
    <property name="show_sql">true</property>
  </session-factory>
  <session-factory name="EF2K">
    <property name="connection.provider">NHibernate.Connection.DriverConnectionProvider</property>
    <property name="dialect">NHibernate.Dialect.MsSql2000Dialect</property>
    <property name="connection.driver_class">NHibernate.Driver.SqlClientDriver</property>
    <property name="connection.connection_string">server=db110\\dbsql2k;database=PCAR;uid=sa;pwd=sa2000;</property>
    <property name="show_sql">true</property>
  </session-factory>
  </hibernate-configuration-x-factories>

the helper class:

    configuration.Configure(HostingEnvironment.MapPath("~/web.config"), catagory);

**Comment by joseph60** [comment]
resolved.
the "\\" cause the problem. It should be 
server=db110\dbsql2k;database=PCAR;uid=sa;pwd=sa2000
